<?php
// Case study detail content, keyed by slug. Six entries (has_data => true)
// use real, verified figures pulled from client SEO/GBP performance
// reports already reviewed for seo.php's case-card section. The other nine
// don't have real results data yet -- their "summary" describes the scope
// of the engagement only (matching what's already shown on the case-studies.php
// listing card), with no invented numbers, until real results are supplied
// to replace them.
return [
    'clever-beavers' => [
        'name' => 'Clever Beavers',
        'tag' => 'Full Suite',
        'image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Clever Beavers Workbooks and Branding',
        'has_data' => false,
        'summary' => 'Clever Beavers is an educational brand creating engaging learning resources for preschool and early childhood education. We designed and built a modern Shopify e-commerce store that showcases its educational workbooks, printable learning resources and digital products, giving parents, teachers and caregivers a fast, fully responsive and playful-yet-professional shopping experience -- from custom homepage sections and product pages to an optimised, secure checkout flow.',
        'services' => ['Custom Shopify Store Development', 'Mobile-First Responsive Design', 'Product & Collection Page Optimization', 'Technical SEO Implementation', 'Payment Gateway Integration', 'Speed & Performance Optimization'],
    ],
    'cafe-calibre' => [
        'name' => 'Cafe Calibre',
        'tag' => 'Hospitality',
        'image' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Cafe Calibre Dining and Dome Reservations',
        'has_data' => false,
        'summary' => 'A full-suite engagement covering brand identity, an online reservation experience and ongoing marketing for Cafe Calibre.',
        'services' => ['AI Design', 'Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'on-crew' => [
        'name' => 'On Crew',
        'tag' => 'Commercial',
        'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'On Crew Professional Team',
        'has_data' => false,
        'summary' => 'A commercial engagement covering website development and ongoing digital marketing for On Crew.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'master-fridge-repairs' => [
        'name' => 'Master Fridge Repairs',
        'tag' => 'Refrigeration',
        'image' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Master Fridge Repairs Service',
        'has_data' => false,
        'summary' => 'A local refrigeration repair business supported with website development and ongoing local search marketing.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'commercial-fridge-repairs-sydney' => [
        'name' => 'Commercial Fridge Repairs Sydney',
        'tag' => 'Sydney Repairs',
        'image' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Commercial Fridge Repairs Sydney',
        'has_data' => true,
        'period' => '20 Jul – 20 Aug 2026',
        'summary' => 'Before this engagement, Commercial Fridge Repairs Sydney had been losing organic value: a large share of the traffic being recorded was coming from outside Australia, and the Google Business Profile had almost no meaningful search presence, not even for branded searches. We rebuilt the website, re-optimised the Business Profile, and built out new suburb, brand and service-focused content across the Sydney commercial refrigeration market. The reporting period below shows the site back on a measurable ranking track across organic search, local search and Google\'s AI features.',
        'stats' => [
            ['102', 'Organic Clicks'],
            ['24.1K', 'Search Impressions'],
            ['+5.3%', 'GBP Growth YoY'],
            ['1.63K', 'AI Feature Impressions'],
        ],
        'services' => ['Full Website Rebuild', 'Google Business Profile Re-optimisation', 'Local SEO & Suburb Content', 'Search Engine Optimization'],
    ],
    'fridge-experts' => [
        'name' => 'Fridge Experts',
        'tag' => 'Experts',
        'image' => 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Fridge Experts Technical Work',
        'has_data' => true,
        'period' => '1 Jun – 21 Aug 2026',
        'summary' => 'Fridge Experts sells and services refrigeration equipment across Sydney, and this quarter\'s SEO campaign moved the site decisively into the high-value part of Google\'s results. Of 33 tracked commercial keywords, 28 now rank on page one and 13 sit in the top three, at an average tracked position of 5.8. Four keywords -- Fridge Repair Normanhurst, Husky Fridge Repairs Sydney, Bar Fridge Repairs and Skipio Fridge Repairs -- hold the number one position outright, and an estimated 85–90% of tracked keywords are already being surfaced inside AI Overviews and AI Mode.',
        'stats' => [
            ['514', 'Organic Clicks'],
            ['28/33', 'Keywords On Page 1'],
            ['5.8', 'Avg. Tracked Position'],
            ['232', 'GBP Interactions'],
        ],
        'services' => ['Local SEO & Keyword Tracking', 'Google Business Profile Management', 'Suburb & Brand Content', 'AI Search Visibility'],
    ],
    'ace-fridge-repairs-sydney' => [
        'name' => 'Ace Fridge Repairs Sydney',
        'tag' => 'Local SEO',
        'image' => 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Ace Fridge Repairs Sydney',
        'has_data' => true,
        'period' => '1 Jul – 8 Aug 2026',
        'summary' => 'Ace Fridge Repairs shows a strong and improving search position, especially on brand-name searches. Ranking #1 for manufacturer names such as CHiQ, GE Appliances, Makeline and Skipio captures customers who\'ve already identified their appliance and are looking for someone to fix it -- the shortest path from search to booked job. 16 of 18 tracked keywords already appear inside Google\'s AI Mode and AI Overview results, including two brand terms surfaced in both AI surfaces simultaneously.',
        'stats' => [
            ['10/18', 'Keywords At #1'],
            ['220', 'Organic Clicks'],
            ['39.3K', 'Search Impressions'],
            ['16/18', 'Visible In AI Results'],
        ],
        'services' => ['Brand & Suburb SEO', 'Google Business Profile Audit', 'AI Search Visibility', 'Local Content Programme'],
    ],
    'sydney-art-flooring' => [
        'name' => 'Sydney Art Flooring',
        'tag' => 'Flooring',
        'image' => 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Sydney Art Flooring Interior',
        'has_data' => false,
        'summary' => 'A flooring specialist supported with website development and ongoing digital marketing to reach more Sydney homeowners and tradespeople.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'fast-fridge-repairs' => [
        'name' => 'Fast Fridge Repairs',
        'tag' => 'Repairs',
        'image' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Fast Fridge Repairs',
        'has_data' => true,
        'period' => '20 Jul – 20 Aug 2026',
        'summary' => 'Fast Fridge Repairs recorded consistent, compounding growth across the reporting period: the second half of the period generated 12% more organic clicks than the first half, with search visibility spanning fridge repair, regas, coolroom and commercial refrigeration terms across Sydney suburbs. Generative AI impressions were distributed across technical guides, the homepage, and emergency repair and local service pages -- a fast-growing channel most local competitors aren\'t tracking yet.',
        'stats' => [
            ['282', 'Organic Clicks'],
            ['34.8K', 'Search Impressions'],
            ['2.68K', 'AI Overview Impressions'],
            ['+5.3%', 'GBP Growth YoY'],
        ],
        'services' => ['Local SEO & Suburb Content', 'Google Business Profile Management', 'AI Search Visibility', 'Website Analytics & Reporting'],
    ],
    'magnet-cleaning-australia' => [
        'name' => 'Magnet Cleaning Australia',
        'tag' => 'Cleaning',
        'image' => 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Magnet Cleaning Australia',
        'has_data' => false,
        'summary' => 'A commercial and residential cleaning business supported with website development and ongoing digital marketing across Australia.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'fast-appliance-repairs' => [
        'name' => 'Fast Appliance Repairs',
        'tag' => 'Appliances',
        'image' => 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Fast Appliance Repairs Kitchen',
        'has_data' => true,
        'period' => '1 Jun – 21 Aug 2026',
        'summary' => 'Fast Appliance Repairs moved from broad visibility into consistent front-page presence this quarter. Across 58 tracked keywords spanning brand, location and service terms, 57 now rank on page one -- an average position of 3.7. The Google Business Profile is doing real work too: 867 interactions including 333 phone calls, close to four inbound calls a day from the listing alone, backed by a full website redesign and 33 Business Profile posts published across the period.',
        'stats' => [
            ['57/58', 'Keywords On Page 1'],
            ['775', 'Organic Clicks'],
            ['333', 'Calls From GBP'],
            ['71.5K', 'Search Impressions'],
        ],
        'services' => ['Website Redesign', 'Weekly Google Business Profile Posting', 'Brand & Location SEO', 'Keyword Rank Tracking'],
    ],
    'royal-fragrances' => [
        'name' => 'Royal Fragrances',
        'tag' => 'Ecommerce',
        'image' => 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Royal Fragrances Perfume Bottle',
        'has_data' => false,
        'summary' => 'An e-commerce fragrance brand supported with online store development, content and ongoing digital marketing.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'becoming-her-with-salma' => [
        'name' => 'Becoming Her With Salma',
        'tag' => 'Lifestyle',
        'image' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Becoming Her With Salma Lifestyle',
        'has_data' => false,
        'summary' => 'A personal lifestyle brand supported with website development, content and ongoing digital marketing to grow its audience.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'northside-coffee' => [
        'name' => 'Northside Coffee',
        'tag' => 'Coffee',
        'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Northside Coffee Shop',
        'has_data' => false,
        'summary' => 'A local coffee shop supported with website development and ongoing digital marketing to grow foot traffic and local awareness.',
        'services' => ['Content Writing', 'Ecommerce Development', 'Graphic Design', 'PPC Advertising', 'Search Engine Optimization', 'Social Media Marketing', 'Website Design'],
    ],
    'freak-eats' => [
        'name' => 'Freak Eats Australia',
        'tag' => 'Food & Eats',
        'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Freak Eats Fast Food',
        'has_data' => true,
        'period' => '1 Jun – 21 Aug 2026',
        'summary' => 'Freak Eats Australia moved from minimal search presence to clear market leadership across Western Sydney in a single quarter. A complete website redesign plus a full Google Business Profile audit and implementation delivered 1,910 additional ranking keywords: of 56 tracked commercial terms, 53 now rank on page one and 36 hold the number one position outright, including the majority of Western Sydney suburb terms. Roughly 95% of tracked queries now appear in Google\'s AI Overviews, and 50–60% are being cited by external AI assistants including ChatGPT, Gemini and Claude.',
        'stats' => [
            ['53/56', 'Keywords On Page 1'],
            ['36', 'Keywords At #1'],
            ['776', 'Organic Clicks'],
            ['258', 'GBP Interactions'],
        ],
        'services' => ['Complete Website Redesign', 'Google Business Profile Audit & Implementation', 'Suburb & Dish-Level Content', 'AI Search Visibility'],
    ],
];
